kind: Deployment
apiVersion: apps/v1
metadata:
    name: juntos-somos-mais-api-deployment
    namespace: staging-apps
spec:
    replicas: 1
    selector:
        matchLabels:
            app: juntos-somos-mais-api
    template:
        metadata:
            labels:
                app: juntos-somos-mais-api
        spec:
            containers:
              - name: juntos-somos-mais-api
                image: docker.io/rempeloliveira/public:juntos-somos-mais-api.1.0.0-staging
                imagePullPolicy: Always
                ports:
                  - containerPort: 8000
                envFrom:
                  - secretRef:
                        name: juntos-somos-mais-api-secrets
                resources:
                    requests:
                        cpu: 250m
                        memory: 512Mi
                    limits:
                        cpu: 500m
                        memory: 1Gi
